resolver: lts-3.22

packages:
- '.'
- location: ../servant-github
  extra-dep: true

extra-deps:
- http-link-header-1.0.3
- jose-0.6.0.3
- concise-0.1.0.0
- monad-time-0.2
- cryptonite-0.11
- memory-0.8
- servant-0.10
- servant-client-0.10
- http-api-data-0.3
- base-compat-0.9.1
- natural-transformation-0.4

flags:

extra-package-dbs: []
